#!/usr/bin/env php
<?php

define('DS', DIRECTORY_SEPARATOR);
$root = dirname(__FILE__) . DS . 'src' . DS;
$toolspath = dirname($root) . DS . 'tools' . DS;

$externs = explode("\n", trim(shell_exec('find ' . escapeshellarg($toolspath . 'externs' . DS) . ' -name *.js')));

$tmppath = sys_get_temp_dir() . DS . 'habrafix' . DS;
mkdir($tmppath);

if ('' == exec('find ' . escapeshellarg($toolspath) . ' -name gcc.jar')) {
	echo "Tools not found. Preparing...\n";

	$cwd = getcwd();
	chdir($toolspath);
	system('./prepare');
	chdir($cwd);
}

$path_gcc    = escapeshellarg(trim(`find ./ -name 'gcc.jar'`));
$path_yui    = escapeshellarg(trim(`find ./ -name 'yui.jar'`));

echo "Parsing manifest.json\n";
$manifest = file_get_contents($root . 'manifest.json');

$manifestObject = json_decode($manifest, true);

$scripts =& $manifestObject['content_scripts'][0];

$compiler = 'java -jar ' . $path_yui;

$cssContent = '';
foreach($scripts['css'] as $css) {
	$cssContent .= file_get_contents($root . $css);
}

file_put_contents($tmppath . 'temp.css', $cssContent);

$compiler .= ' ' . escapeshellarg($tmppath . 'temp.css');

echo "Compressing .css\n";
$css = shell_exec($compiler);

unlink($tmppath . 'temp.css');

$compiler = 'java -jar ' . $path_gcc . ' --compilation_level ADVANCED_OPTIMIZATIONS ' .
	'--warning_level QUIET';

foreach($scripts['js'] as $js) {
	if ($js == 'js/debug.js') {
		continue;
	}

	$compiler .= ' --js ' . escapeshellarg($root . $js);
}

echo "Compressing .js\n";
$js = shell_exec($compiler);

$scripts['js']  = array('habrafix.js');
$scripts['css'] = array('habrafix.css');

echo "Preparing background page\n";
$backgroundPage = $manifestObject['background_page'];
$background = file_get_contents($root . $backgroundPage);

if (preg_match_all('@script src="(.*?)"@', $background, $matches)) {
	$cm = array_pop($matches);
	
	$compiler = 'java -jar ' . $path_gcc . ' --compilation_level ADVANCED_OPTIMIZATIONS ' .
		'--warning_level QUIET';
		
	foreach($cm as $file) {
		$compiler .= ' --js ' . escapeshellarg($root . $file);
	}	

	foreach($externs as $extern) {
		$compiler .= ' --externs ' . escapeshellarg($extern);
	}

	$background = '<html><body><script>' . shell_exec($compiler) . '</script></body></html>';
	
	file_put_contents($tmppath . $backgroundPage, $background);
}

$manifestOut = json_encode($manifestObject);
$manifestOut = str_replace('\/', '/', $manifestOut);

file_put_contents($tmppath . 'manifest.json', $manifestOut);
file_put_contents($tmppath . 'habrafix.js', $js);
file_put_contents($tmppath . 'habrafix.css', $css);

shell_exec('cp -R ' . escapeshellarg($root . 'icons') . ' ' . escapeshellarg($tmppath));

$cwd = getcwd();

chdir($tmppath);

echo "Compressing extension\n";
$cmd = 'zip -9 -r ' . escapeshellarg($cwd . DS . 'ext.zip') . ' ./';
shell_exec($cmd);

chdir($cwd);

shell_exec('rm -rf ' . escapeshellarg($tmppath));

echo "Done\n";
