#!/bin/sh

# google closure compiler (for javascript)
wget http://closure-compiler.googlecode.com/files/compiler-latest.zip -O ./tmp.zip
unzip tmp.zip compiler.jar
rm tmp.zip

mv compiler.jar gcc.jar

# yui compressor (for css)
wget http://yui.zenfs.com/releases/yuicompressor/yuicompressor-2.4.6.zip -O ./tmp.zip
unzip -j tmp.zip yuicompressor-2.4.6/build/yuicompressor-2.4.6.jar
rm tmp.zip

mv yuicompressor-2.4.6.jar yui.jar
